import type { Document } from '@/types/document';

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'doc-001',
    tenantId: 'tenant-001',
    originalFileName: 'contrato-fornecedor-2024.pdf',
    displayName: 'Contrato Fornecedor 2024',
    documentType: 'Contrato',
    status: 'processed',
    version: 2,
    currentVersionId: 'ver-002',
    ownerUserId: 'user-001',
    ownerName: 'Administrador DOQYN',
    area: 'Jurídico',
    accessGroups: ['Jurídico', 'Financeiro'],
    metadata: { pages: 12, language: 'pt-BR' },
    processingStatus: 'completed',
    createdAt: '2025-06-15T10:30:00Z',
    updatedAt: '2025-06-18T14:22:00Z',
  },
  {
    id: 'doc-002',
    tenantId: 'tenant-001',
    originalFileName: 'nf-transporte-jun.pdf',
    displayName: 'NF Transporte — Junho',
    documentType: 'Nota Fiscal',
    status: 'analyzing',
    version: 1,
    currentVersionId: 'ver-003',
    ownerUserId: 'user-001',
    ownerName: 'Administrador DOQYN',
    area: 'Frete',
    accessGroups: ['Frete', 'Financeiro'],
    metadata: {},
    processingStatus: 'in_progress',
    createdAt: '2025-06-20T09:15:00Z',
    updatedAt: '2025-06-20T09:15:00Z',
  },
  {
    id: 'doc-003',
    tenantId: 'tenant-001',
    originalFileName: 'politica-rh-v3.docx',
    displayName: 'Política de Benefícios RH',
    documentType: 'Política Interna',
    status: 'pending_review',
    version: 3,
    currentVersionId: 'ver-005',
    ownerUserId: 'user-001',
    ownerName: 'Administrador DOQYN',
    area: 'RH',
    accessGroups: ['RH'],
    metadata: { revision: 'v3' },
    processingStatus: 'completed',
    createdAt: '2025-06-10T16:00:00Z',
    updatedAt: '2025-06-19T11:45:00Z',
  },
  {
    id: 'doc-004',
    tenantId: 'tenant-001',
    originalFileName: 'relatorio-financeiro-q2.xlsx',
    displayName: 'Relatório Financeiro Q2',
    documentType: 'Relatório',
    status: 'needs_review',
    version: 1,
    currentVersionId: 'ver-006',
    ownerUserId: 'user-001',
    ownerName: 'Administrador DOQYN',
    area: 'Financeiro',
    accessGroups: ['Financeiro'],
    metadata: {},
    processingStatus: 'completed',
    createdAt: '2025-06-21T08:00:00Z',
    updatedAt: '2025-06-21T08:00:00Z',
  },
];
