/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        doqyn: {
          bg: 'var(--bg-app)',
          sidebar: 'var(--bg-sidebar)',
          surface: 'var(--bg-surface)',
          panel: 'var(--bg-surface)',
          card: 'var(--bg-surface-2)',
          panelSoft: 'var(--bg-surface-3)',
          overlay: 'var(--bg-surface-2)',
          border: 'var(--border-default)',
          'border-subtle': 'var(--border-subtle)',
          'border-strong': 'var(--border-strong)',
          text: 'var(--text-primary)',
          foreground: 'var(--text-primary)',
          muted: 'var(--text-secondary)',
          subtle: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          hint: 'var(--text-hint)',
          action: 'var(--accent-active)',
          actionHover: 'var(--text-secondary)',
          primary: 'var(--accent-active)',
          'primary-hover': 'var(--text-secondary)',
          'primary-soft': 'var(--accent-active-bg)',
          'primary-bg': 'var(--accent-active-bg)',
          success: 'var(--status-ok-text)',
          'success-bg': 'var(--status-ok-bg)',
          'success-border': 'var(--status-ok-border)',
          warning: 'var(--status-warn-text)',
          'warning-bg': 'var(--status-warn-bg)',
          'warning-border': 'var(--status-warn-border)',
          danger: 'var(--status-danger-text)',
          'danger-bg': 'var(--status-danger-bg)',
          'danger-border': 'var(--status-danger-border)',
          hover: 'var(--overlay-hover)',
          active: 'var(--overlay-active)',
          logo: 'var(--logo-text)',
          'logo-muted': 'var(--logo-muted)',
          'accent-active': 'var(--accent-active)',
          'accent-active-bg': 'var(--accent-active-bg)',
        },
      },
      fontFamily: {
        sans: ['Geist Variable', 'Geist Sans', 'system-ui', 'sans-serif'],
        logo: ['Geist Variable', 'Geist Sans', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono Variable', 'Geist Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        card: 'none',
        modal: 'var(--shadow-modal)',
      },
    },
  },
  plugins: [],
};
