/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        doqyn: {
          bg: 'var(--bg-app)',
          chrome: 'var(--bg-chrome)',
          shell: 'var(--bg-shell)',
          canvas: 'var(--bg-canvas)',
          'thumbnail-chrome': 'var(--bg-thumbnail-chrome)',
          sidebar: 'var(--bg-sidebar)',
          surface: 'var(--bg-surface)',
          'surface-hover': 'var(--bg-surface-hover)',
          panel: 'var(--bg-surface)',
          card: 'var(--bg-surface-2)',
          panelSoft: 'var(--bg-surface-3)',
          overlay: 'var(--bg-surface-2)',
          border: 'var(--border-default)',
          'border-subtle': 'var(--border-subtle)',
          'border-strong': 'var(--border-strong)',
          'border-hairline': 'var(--border-hairline)',
          text: 'var(--text-primary)',
          foreground: 'var(--text-primary)',
          muted: 'var(--text-secondary)',
          subtle: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          hint: 'var(--text-hint)',
          action: 'var(--accent-active)',
          actionHover: 'var(--accent-hover)',
          primary: 'var(--accent-active)',
          'primary-hover': 'var(--accent-hover)',
          'primary-soft': 'var(--accent-active-bg)',
          'primary-bg': 'var(--accent-active-bg)',
          success: 'var(--status-ok-text)',
          'success-bg': 'var(--status-ok-bg)',
          'success-border': 'var(--status-ok-border)',
          'success-dot': 'var(--status-ok-dot)',
          warning: 'var(--status-warn-text)',
          'warning-bg': 'var(--status-warn-bg)',
          'warning-border': 'var(--status-warn-border)',
          'warning-dot': 'var(--status-warn-dot)',
          danger: 'var(--status-danger-text)',
          'danger-bg': 'var(--status-danger-bg)',
          'danger-border': 'var(--status-danger-border)',
          'danger-dot': 'var(--status-danger-dot)',
          pending: 'var(--status-pending-text)',
          'pending-bg': 'var(--status-pending-bg)',
          'pending-border': 'var(--status-pending-border)',
          'pending-dot': 'var(--status-pending-dot)',
          info: 'var(--status-info-text)',
          'info-bg': 'var(--status-info-bg)',
          'info-border': 'var(--status-info-border)',
          'info-dot': 'var(--status-info-dot)',
          neutral: 'var(--status-neutral-text)',
          'neutral-bg': 'var(--status-neutral-bg)',
          'neutral-border': 'var(--status-neutral-border)',
          'neutral-dot': 'var(--status-neutral-dot)',
          hover: 'var(--overlay-hover)',
          active: 'var(--overlay-active)',
          logo: 'var(--logo-text)',
          'logo-muted': 'var(--logo-muted)',
          'accent-active': 'var(--accent-active)',
          'accent-active-bg': 'var(--accent-active-bg)',
          'accent-hover': 'var(--accent-hover)',
          'on-accent': 'var(--text-on-accent)',
          selected: 'var(--bg-selected)',
          'sidebar-selected': 'var(--sidebar-selected-bg)',
          'sidebar-selected-border': 'var(--sidebar-selected-border)',
          'sidebar-selected-text': 'var(--sidebar-selected-text)',
          'sidebar-selected-icon': 'var(--sidebar-selected-icon)',
          'sidebar-item-hover': 'var(--sidebar-item-hover-bg)',
          'new-button': 'var(--new-button-bg)',
          'new-button-hover': 'var(--new-button-bg-hover)',
          'new-button-active': 'var(--new-button-bg-active)',
          'new-button-text': 'var(--new-button-text)',
          'new-button-border': 'var(--new-button-border)',
          'new-menu': 'var(--new-menu-bg)',
          'new-menu-icon': 'var(--new-menu-icon)',
          premium: 'var(--accent-premium)',
          'premium-bg': 'var(--accent-premium-bg)',
          'premium-border': 'var(--accent-premium-border)',
          'on-premium': 'var(--text-on-premium)',
          cta: 'var(--cta-bg)',
          'cta-hover': 'var(--cta-bg-hover)',
          'cta-active': 'var(--cta-bg-active)',
          'cta-text': 'var(--cta-text)',
        },
      },
      fontFamily: {
        sans: ['var(--font-body)'],
        display: ['var(--font-display)'],
        body: ['var(--font-body)'],
        logo: ['var(--font-display)'],
        mono: ['var(--font-family-mono)'],
      },
      fontSize: {
        eyebrow: [
          'var(--text-eyebrow)',
          {
            lineHeight: 'var(--leading-eyebrow)',
            letterSpacing: 'var(--tracking-eyebrow)',
            fontWeight: 'var(--weight-eyebrow)',
          },
        ],
        display: [
          'var(--text-display)',
          {
            lineHeight: 'var(--leading-display)',
            letterSpacing: 'var(--tracking-display)',
            fontWeight: 'var(--weight-display)',
          },
        ],
        h1: [
          'var(--text-h1)',
          {
            lineHeight: 'var(--leading-h1)',
            letterSpacing: 'var(--tracking-h1)',
            fontWeight: 'var(--weight-h1)',
          },
        ],
        h2: [
          'var(--text-h2)',
          {
            lineHeight: 'var(--leading-h2)',
            letterSpacing: 'var(--tracking-h2)',
            fontWeight: 'var(--weight-h2)',
          },
        ],
        body: [
          'var(--text-body)',
          { lineHeight: 'var(--leading-body)', fontWeight: 'var(--weight-body)' },
        ],
        label: [
          'var(--text-label)',
          {
            lineHeight: 'var(--leading-label)',
            letterSpacing: 'var(--tracking-label)',
            fontWeight: 'var(--weight-label)',
          },
        ],
        caption: [
          'var(--text-caption)',
          { lineHeight: 'var(--leading-caption)', fontWeight: 'var(--weight-caption)' },
        ],
        xs: ['var(--text-caption)', { lineHeight: 'var(--leading-caption)' }],
        sm: ['var(--text-body)', { lineHeight: 'var(--leading-body)' }],
        base: ['var(--text-body)', { lineHeight: 'var(--leading-body)' }],
        lg: ['var(--text-h2)', { lineHeight: 'var(--leading-h2)' }],
        xl: ['var(--text-h1)', { lineHeight: 'var(--leading-h1)' }],
        '2xl': ['var(--text-display)', { lineHeight: 'var(--leading-display)' }],
      },
      fontWeight: {
        normal: 'var(--weight-body)',
        medium: 'var(--weight-label)',
        semibold: 'var(--weight-h2)',
        bold: '700',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        shell: 'var(--radius-shell)',
        workspace: 'var(--radius-workspace)',
        'new-button': 'var(--radius-new-button)',
      },
      spacing: {
        field: 'var(--field-height)',
        'icon-btn': 'var(--icon-button-size)',
      },
      height: {
        field: 'var(--field-height)',
        'icon-btn': 'var(--icon-button-size)',
      },
      width: {
        'icon-btn': 'var(--icon-button-size)',
      },
      minHeight: {
        field: 'var(--field-height)',
        'icon-btn': 'var(--icon-button-size)',
      },
      minWidth: {
        'icon-btn': 'var(--icon-button-size)',
      },
      boxShadow: {
        card: 'var(--shadow-elevation-1)',
        modal: 'var(--shadow-modal)',
        dropdown: 'var(--shadow-dropdown)',
        sm: 'var(--shadow-sm)',
        shell: 'var(--shadow-shell)',
        'card-hover': 'var(--shadow-card-hover)',
        'action-glow': 'var(--shadow-action-glow)',
        'elevation-1': 'var(--shadow-elevation-1)',
        'elevation-2': 'var(--shadow-elevation-2)',
        'sticky-footer': 'var(--shadow-sticky-footer)',
        'new-button': 'var(--shadow-new-button)',
        'new-button-hover': 'var(--shadow-new-button-hover)',
      },
    },
  },
  plugins: [],
};
