import type { MongoDocumentClass, MongoDocumentRule } from '../types.js';
import { DEV_TENANT_ID } from '../constants.js';

const now = new Date();

function viewOnlyPermissions(view: string[]) {
  return {
    view,
    download: [] as string[],
    update: [] as string[],
    audit: [] as string[],
    share: [] as string[],
  };
}

function classPresentation(input: {
  iconKey: string;
  color: string;
  notifyGroups: string[];
}) {
  return {
    iconKey: input.iconKey,
    color: input.color,
    notifyOnUpdate: true,
    notifyGroups: input.notifyGroups,
  };
}

export const SEED_DOCUMENT_CLASSES: MongoDocumentClass[] = [
  {
    _id: 'class_contract_supplier',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    name: 'Contrato de Fornecedor',
    slug: 'contrato-de-fornecedor',
    description:
      'Contratos firmados com fornecedores, prestadores de serviço e parceiros comerciais.',
    active: true,
    ...classPresentation({
      iconKey: 'file-text',
      color: 'blue',
      notifyGroups: ['group_juridico', 'group_financeiro'],
    }),
    keywords: [
      'contrato',
      'contratante',
      'contratada',
      'fornecedor',
      'prestação de serviços',
      'prestacao de servicos',
      'vigência',
      'vigencia',
      'cláusula',
      'clausula',
      'assinatura',
    ],
    negativeKeywords: [
      'nota fiscal',
      'nf-e',
      'ordem de compra',
      'acordo de confidencialidade',
      'nda',
      'não divulgação',
      'nao divulgacao',
    ],
    permissions: viewOnlyPermissions(['group_juridico', 'group_financeiro']),
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'class_invoice',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    name: 'Nota Fiscal',
    slug: 'nota-fiscal',
    description: 'Documentos fiscais, notas de serviço ou produto.',
    active: true,
    ...classPresentation({
      iconKey: 'receipt',
      color: 'green',
      notifyGroups: ['group_financeiro'],
    }),
    keywords: [
      'nota fiscal',
      'nf-e',
      'nfs-e',
      'emissão',
      'emissao',
      'emitente',
      'destinatário',
      'destinatario',
      'valor total',
      'chave de acesso',
    ],
    negativeKeywords: ['contrato de prestação', 'ordem de compra'],
    permissions: viewOnlyPermissions(['group_financeiro']),
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'class_purchase_order',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    name: 'Ordem de Compra',
    slug: 'ordem-de-compra',
    description: 'Pedidos e ordens de compra emitidos pela empresa.',
    active: true,
    ...classPresentation({
      iconKey: 'file-text',
      color: 'red',
      notifyGroups: ['group_compras'],
    }),
    keywords: [
      'ordem de compra',
      'pedido de compra',
      'comprador',
      'fornecedor',
      'item',
      'quantidade',
      'valor unitário',
      'valor unitario',
    ],
    negativeKeywords: ['nota fiscal', 'contrato'],
    permissions: viewOnlyPermissions(['group_compras', 'group_financeiro']),
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'class_confidentiality_agreement',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    name: 'Acordo de Confidencialidade',
    slug: 'acordo-de-confidencialidade',
    description:
      'Documentos de confidencialidade, NDA, acordos de não divulgação, não concorrência, não aliciamento e proteção de informações confidenciais.',
    active: true,
    ...classPresentation({
      iconKey: 'shield-check',
      color: 'purple',
      notifyGroups: ['group_juridico'],
    }),
    keywords: [
      'acordo de confidencialidade',
      'confidencialidade',
      'NDA',
      'non-disclosure agreement',
      'não divulgação',
      'nao divulgacao',
      'informação confidencial',
      'informacoes confidenciais',
      'revelador',
      'receptor',
      'parte reveladora',
      'parte receptora',
      'não concorrência',
      'nao concorrencia',
      'não aliciamento',
      'nao aliciamento',
      'sigilo',
      'segredo comercial',
      'proteção de informações',
      'protecao de informacoes',
    ],
    negativeKeywords: [
      'nota fiscal',
      'DANFE',
      'chave de acesso',
      'ordem de compra',
      'pedido de compra',
      'boleto',
      'fatura',
    ],
    permissions: viewOnlyPermissions(['group_juridico', 'group_diretoria']),
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'class_boleto',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    name: 'Boleto',
    slug: 'boleto',
    description: 'Boletos bancários, cobranças e títulos de pagamento.',
    active: true,
    ...classPresentation({
      iconKey: 'file-invoice',
      color: 'green',
      notifyGroups: ['group_financeiro'],
    }),
    keywords: [
      'boleto',
      'boleto bancário',
      'boleto bancario',
      'linha digitável',
      'linha digitavel',
      'código de barras',
      'codigo de barras',
      'vencimento',
      'beneficiário',
      'beneficiario',
      'pagador',
      'valor do documento',
    ],
    negativeKeywords: ['nota fiscal', 'contrato', 'nda', 'acordo de confidencialidade'],
    permissions: viewOnlyPermissions(['group_financeiro']),
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'class_commercial_proposal',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    name: 'Proposta Comercial',
    slug: 'proposta-comercial',
    description: 'Propostas comerciais, cotações e ofertas enviadas a clientes ou fornecedores.',
    active: true,
    ...classPresentation({
      iconKey: 'file-text',
      color: 'amber',
      notifyGroups: ['group_compras'],
    }),
    keywords: [
      'proposta comercial',
      'proposta',
      'cotação',
      'cotacao',
      'oferta comercial',
      'orçamento',
      'orcamento',
      'condições comerciais',
      'condicoes comerciais',
      'validade da proposta',
    ],
    negativeKeywords: ['nota fiscal', 'boleto', 'contrato de fornecedor'],
    permissions: viewOnlyPermissions(['group_compras', 'group_diretoria']),
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'class_internal_policy',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    name: 'Política Interna',
    slug: 'politica-interna',
    description: 'Políticas internas, normas corporativas e diretrizes da empresa.',
    active: true,
    ...classPresentation({
      iconKey: 'shield-check',
      color: 'blue',
      notifyGroups: ['group_rh'],
    }),
    keywords: [
      'política interna',
      'politica interna',
      'norma corporativa',
      'diretriz',
      'código de conduta',
      'codigo de conduta',
      'regulamento interno',
      'procedimento interno',
    ],
    negativeKeywords: ['nota fiscal', 'boleto', 'contrato', 'proposta comercial'],
    permissions: viewOnlyPermissions(['group_rh', 'group_diretoria']),
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
];

export const SEED_DOCUMENT_RULES: MongoDocumentRule[] = [
  {
    _id: 'rule_contract_supplier_v1',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    classId: 'class_contract_supplier',
    version: 1,
    active: true,
    fields: [
      {
        key: 'fornecedor',
        label: 'Fornecedor',
        type: 'string',
        required: true,
        aliases: ['contratada', 'fornecedor', 'prestador', 'empresa contratada'],
        description: 'Nome da empresa fornecedora ou prestadora de serviço.',
      },
      {
        key: 'cnpj',
        label: 'CNPJ',
        type: 'string',
        required: false,
        aliases: ['CNPJ', 'CNPJ/MF', 'cadastro nacional'],
        description: 'CNPJ da empresa fornecedora.',
      },
      {
        key: 'data_assinatura',
        label: 'Data de assinatura',
        type: 'date',
        required: false,
        aliases: ['data de assinatura', 'assinado em', 'celebrado em'],
        description: 'Data de assinatura ou celebração do contrato.',
      },
      {
        key: 'valor_total',
        label: 'Valor total',
        type: 'currency',
        required: false,
        aliases: ['valor total', 'valor do contrato', 'preço', 'preco', 'remuneração'],
        description: 'Valor total do contrato.',
      },
      {
        key: 'vigencia',
        label: 'Vigência',
        type: 'string',
        required: false,
        aliases: ['vigência', 'vigencia', 'prazo', 'validade'],
        description: 'Prazo ou período de vigência do contrato.',
      },
    ],
    namingTemplate: 'Contrato_{fornecedor}_{data_assinatura}_v{version}',
    minimumConfidence: 0.7,
    onLowConfidence: 'requires_review',
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'rule_invoice_v1',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    classId: 'class_invoice',
    version: 1,
    active: true,
    fields: [
      {
        key: 'numero_nota',
        label: 'Número da nota',
        type: 'string',
        required: true,
        aliases: ['número', 'numero', 'nº', 'nota fiscal nº', 'nf-e nº'],
        description: 'Número identificador da nota fiscal.',
      },
      {
        key: 'fornecedor',
        label: 'Fornecedor',
        type: 'string',
        required: true,
        aliases: ['emitente', 'prestador', 'fornecedor', 'razão social', 'razao social'],
        description: 'Empresa emissora da nota fiscal.',
      },
      {
        key: 'cnpj_emitente',
        label: 'CNPJ emitente',
        type: 'string',
        required: false,
        aliases: ['CNPJ', 'CNPJ emitente', 'CPF/CNPJ'],
        description: 'CNPJ da empresa emissora.',
      },
      {
        key: 'data_emissao',
        label: 'Data de emissão',
        type: 'date',
        required: false,
        aliases: ['data de emissão', 'data de emissao', 'emissão', 'emissao', 'emitida em'],
        description: 'Data de emissão da nota fiscal.',
      },
      {
        key: 'valor_total',
        label: 'Valor total',
        type: 'currency',
        required: true,
        aliases: ['valor total', 'total da nota', 'valor dos serviços', 'valor líquido'],
        description: 'Valor total da nota fiscal.',
      },
    ],
    namingTemplate: 'Nota_Fiscal_{fornecedor}_{numero_nota}_{data_emissao}_v{version}',
    minimumConfidence: 0.7,
    onLowConfidence: 'requires_review',
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'rule_purchase_order_v1',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    classId: 'class_purchase_order',
    version: 1,
    active: true,
    fields: [
      {
        key: 'numero_pedido',
        label: 'Número do pedido',
        type: 'string',
        required: true,
        aliases: ['número do pedido', 'numero do pedido', 'pedido nº', 'ordem de compra nº', 'OC'],
        description: 'Número da ordem ou pedido de compra.',
      },
      {
        key: 'fornecedor',
        label: 'Fornecedor',
        type: 'string',
        required: true,
        aliases: ['fornecedor', 'empresa', 'razão social', 'razao social'],
        description: 'Nome do fornecedor da ordem de compra.',
      },
      {
        key: 'data_pedido',
        label: 'Data do pedido',
        type: 'date',
        required: false,
        aliases: ['data do pedido', 'data de emissão', 'data de emissao', 'emitido em'],
        description: 'Data em que a ordem de compra foi emitida.',
      },
      {
        key: 'valor_total',
        label: 'Valor total',
        type: 'currency',
        required: false,
        aliases: ['valor total', 'total', 'valor do pedido'],
        description: 'Valor total da ordem de compra.',
      },
    ],
    namingTemplate: 'Ordem_Compra_{fornecedor}_{numero_pedido}_{data_pedido}_v{version}',
    minimumConfidence: 0.7,
    onLowConfidence: 'requires_review',
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'rule_confidentiality_agreement_v1',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    classId: 'class_confidentiality_agreement',
    version: 1,
    active: true,
    fields: [
      {
        key: 'parte_reveladora',
        label: 'Parte reveladora',
        type: 'string',
        required: false,
        aliases: [
          'parte reveladora',
          'revelador',
          'divulgador',
          'contratante',
          'proprietário das informações',
          'proprietario das informacoes',
        ],
        description: 'Parte que revela ou disponibiliza as informações confidenciais.',
      },
      {
        key: 'parte_receptora',
        label: 'Parte receptora',
        type: 'string',
        required: true,
        aliases: [
          'parte receptora',
          'receptor',
          'recebedor',
          'contratado',
          'destinatário',
          'destinatario',
        ],
        description: 'Parte que recebe e deve proteger as informações confidenciais.',
      },
      {
        key: 'cpf_cnpj_receptora',
        label: 'CPF/CNPJ da parte receptora',
        type: 'string',
        required: false,
        aliases: ['CPF', 'CNPJ', 'CPF/MF', 'CNPJ/MF', 'inscrito no CPF', 'inscrita no CNPJ'],
        description: 'CPF ou CNPJ da parte receptora, quando informado no documento.',
      },
      {
        key: 'data_assinatura',
        label: 'Data de assinatura',
        type: 'date',
        required: false,
        aliases: ['data de assinatura', 'assinado em', 'firmado em', 'celebrado em'],
        description: 'Data de assinatura ou celebração do acordo.',
      },
      {
        key: 'prazo_vigencia',
        label: 'Prazo de vigência',
        type: 'string',
        required: false,
        aliases: ['vigência', 'vigencia', 'prazo de vigência', 'prazo de vigencia', 'válido por'],
        description: 'Prazo de vigência do acordo.',
      },
      {
        key: 'multa_penalidade',
        label: 'Multa ou penalidade',
        type: 'currency',
        required: false,
        aliases: ['multa', 'penalidade', 'perdas e danos', 'indenização', 'indenizacao'],
        description: 'Valor de multa ou penalidade prevista no acordo.',
      },
    ],
    namingTemplate: 'NDA_{parte_reveladora}_e_{parte_receptora}_{data_assinatura}_v{version}',
    minimumConfidence: 0.7,
    onLowConfidence: 'requires_review',
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'rule_boleto_v1',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    classId: 'class_boleto',
    version: 1,
    active: true,
    fields: [
      {
        key: 'beneficiario',
        label: 'Beneficiário',
        type: 'string',
        required: true,
        aliases: ['beneficiário', 'beneficiario', 'cedente', 'favorecido'],
        description: 'Nome do beneficiário do boleto.',
      },
      {
        key: 'pagador',
        label: 'Pagador',
        type: 'string',
        required: false,
        aliases: ['pagador', 'sacado', 'devedor'],
        description: 'Nome do pagador ou sacado.',
      },
      {
        key: 'data_vencimento',
        label: 'Data de vencimento',
        type: 'date',
        required: false,
        aliases: ['vencimento', 'data de vencimento', 'vence em'],
        description: 'Data de vencimento do boleto.',
      },
      {
        key: 'valor_documento',
        label: 'Valor do documento',
        type: 'currency',
        required: true,
        aliases: ['valor do documento', 'valor', 'valor cobrado'],
        description: 'Valor nominal do boleto.',
      },
    ],
    namingTemplate: 'Boleto_{beneficiario}_{data_vencimento}_v{version}',
    minimumConfidence: 0.7,
    onLowConfidence: 'requires_review',
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'rule_commercial_proposal_v1',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    classId: 'class_commercial_proposal',
    version: 1,
    active: true,
    fields: [
      {
        key: 'cliente',
        label: 'Cliente',
        type: 'string',
        required: true,
        aliases: ['cliente', 'destinatário', 'destinatario', 'empresa'],
        description: 'Cliente ou destinatário da proposta.',
      },
      {
        key: 'data_proposta',
        label: 'Data da proposta',
        type: 'date',
        required: false,
        aliases: ['data da proposta', 'emitida em', 'data de emissão', 'data de emissao'],
        description: 'Data de emissão da proposta.',
      },
      {
        key: 'valor_total',
        label: 'Valor total',
        type: 'currency',
        required: false,
        aliases: ['valor total', 'valor da proposta', 'investimento'],
        description: 'Valor total proposto.',
      },
      {
        key: 'validade',
        label: 'Validade',
        type: 'string',
        required: false,
        aliases: ['validade', 'válida por', 'valida por', 'prazo de validade'],
        description: 'Prazo de validade da proposta.',
      },
    ],
    namingTemplate: 'Proposta_{cliente}_{data_proposta}_v{version}',
    minimumConfidence: 0.7,
    onLowConfidence: 'requires_review',
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'rule_internal_policy_v1',
    tenantId: DEV_TENANT_ID,
    companyId: DEV_TENANT_ID,
    classId: 'class_internal_policy',
    version: 1,
    active: true,
    fields: [
      {
        key: 'titulo',
        label: 'Título',
        type: 'string',
        required: true,
        aliases: ['título', 'titulo', 'nome da política', 'nome da politica'],
        description: 'Título ou nome da política interna.',
      },
      {
        key: 'versao',
        label: 'Versão',
        type: 'string',
        required: false,
        aliases: ['versão', 'versao', 'revisão', 'revisao'],
        description: 'Versão ou revisão da política.',
      },
      {
        key: 'data_vigencia',
        label: 'Data de vigência',
        type: 'date',
        required: false,
        aliases: ['vigência', 'vigencia', 'vigente a partir de', 'data de vigência'],
        description: 'Data de início de vigência da política.',
      },
      {
        key: 'area_responsavel',
        label: 'Área responsável',
        type: 'string',
        required: false,
        aliases: ['área responsável', 'area responsavel', 'departamento', 'RH', 'jurídico'],
        description: 'Área ou departamento responsável pela política.',
      },
    ],
    namingTemplate: 'Politica_{titulo}_{data_vigencia}_v{version}',
    minimumConfidence: 0.7,
    onLowConfidence: 'requires_review',
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
  },
];

/** Campos de apresentação backfillados apenas se ausentes (não sobrescreve edições da UI). */
export const DOCUMENT_CLASS_PRESENTATION_BACKFILL_FIELDS = [
  'slug',
  'iconKey',
  'color',
  'notifyOnUpdate',
  'notifyGroups',
] as const;

export function getDocumentClassPresentationBackfill(docClass: MongoDocumentClass) {
  return {
    slug: docClass.slug,
    iconKey: docClass.iconKey,
    color: docClass.color,
    notifyOnUpdate: docClass.notifyOnUpdate,
    notifyGroups: docClass.notifyGroups,
  };
}
