import type {
  AuditEvent,
  CompanyMember,
  DocumentCategory,
  Group,
  PendingApproval,
} from '@/types/rules';

export const CURRENT_COMPANY_ID = 'acme-industria';
export const CURRENT_USER_ROLE = 'admin' as const;
export const CURRENT_USER_NAME = 'Mariana Ferreira';

export const INITIAL_GROUPS: Group[] = [
  {
    id: 'grp_juridico',
    companyId: CURRENT_COMPANY_ID,
    name: 'Jurídico',
    color: 'blue',
    createdAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'grp_financeiro',
    companyId: CURRENT_COMPANY_ID,
    name: 'Financeiro',
    color: 'green',
    createdAt: '2026-05-01T10:01:00Z',
  },
  {
    id: 'grp_rh',
    companyId: CURRENT_COMPANY_ID,
    name: 'RH',
    color: 'amber',
    createdAt: '2026-05-01T10:02:00Z',
  },
  {
    id: 'grp_compras',
    companyId: CURRENT_COMPANY_ID,
    name: 'Compras',
    color: 'red',
    createdAt: '2026-05-01T10:03:00Z',
  },
  {
    id: 'grp_diretoria',
    companyId: CURRENT_COMPANY_ID,
    name: 'Diretoria',
    color: 'purple',
    createdAt: '2026-05-01T10:04:00Z',
  },
];

export const INITIAL_MEMBERS: CompanyMember[] = [
  {
    id: 'mbr_mariana',
    companyId: CURRENT_COMPANY_ID,
    name: 'Mariana Ferreira',
    email: 'mariana@acme.com',
    position: 'Administradora',
    role: 'admin',
    status: 'active',
    groupIds: ['grp_juridico', 'grp_financeiro'],
    lastAccessAt: 'Hoje, 09:17',
    createdAt: '2026-01-15T08:00:00Z',
    approvedBy: 'Sistema',
    approvedAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'mbr_carlos',
    companyId: CURRENT_COMPANY_ID,
    name: 'Carlos Souza',
    email: 'carlos@acme.com',
    position: 'Analista Financeiro',
    role: 'member',
    status: 'active',
    groupIds: ['grp_financeiro'],
    lastAccessAt: 'Ontem, 17:42',
    createdAt: '2026-02-10T10:00:00Z',
    approvedBy: 'Mariana Ferreira',
    approvedAt: '2026-02-10T10:30:00Z',
  },
  {
    id: 'mbr_joao',
    companyId: CURRENT_COMPANY_ID,
    name: 'João Almeida',
    email: 'joao@acme.com',
    position: 'Compras',
    role: 'member',
    status: 'active',
    groupIds: ['grp_compras'],
    lastAccessAt: 'Hoje, 08:55',
    createdAt: '2026-03-05T14:00:00Z',
    approvedBy: 'Mariana Ferreira',
    approvedAt: '2026-03-05T14:30:00Z',
  },
  {
    id: 'mbr_ana',
    companyId: CURRENT_COMPANY_ID,
    name: 'Ana Oliveira',
    email: 'ana@acme.com',
    position: 'RH',
    role: 'member',
    status: 'pending',
    groupIds: [],
    lastAccessAt: undefined,
    createdAt: '2026-06-22T10:00:00Z',
  },
  {
    id: 'mbr_pedro',
    companyId: CURRENT_COMPANY_ID,
    name: 'Pedro Lima',
    email: 'pedro@acme.com',
    position: 'Auditoria Interna',
    role: 'auditor',
    status: 'pending',
    groupIds: [],
    lastAccessAt: undefined,
    createdAt: '2026-06-21T15:00:00Z',
  },
];

export const INITIAL_PENDING_APPROVALS: PendingApproval[] = [
  {
    id: 'pend_ana',
    companyId: CURRENT_COMPANY_ID,
    name: 'Ana Oliveira',
    email: 'ana@acme.com',
    domain: 'acme.com',
    requestedAt: 'Hoje, 10:22',
    method: 'access_request',
    requestedGroups: [],
    position: 'RH',
    role: 'member',
  },
  {
    id: 'pend_pedro',
    companyId: CURRENT_COMPANY_ID,
    name: 'Pedro Lima',
    email: 'pedro@acme.com',
    domain: 'acme.com',
    requestedAt: 'Ontem, 15:10',
    method: 'invite',
    requestedGroups: [],
    position: 'Auditoria Interna',
    role: 'auditor',
  },
];

export const INITIAL_CATEGORIES: DocumentCategory[] = [
  {
    id: 'cat_contrato',
    companyId: CURRENT_COMPANY_ID,
    name: 'Contrato',
    icon: 'file-text',
    accessGroupIds: ['grp_juridico', 'grp_financeiro'],
    notifyGroupIds: ['grp_juridico', 'grp_financeiro'],
    createdAt: '2026-05-01T10:10:00Z',
  },
  {
    id: 'cat_nf',
    companyId: CURRENT_COMPANY_ID,
    name: 'Nota Fiscal',
    icon: 'receipt',
    accessGroupIds: ['grp_financeiro'],
    notifyGroupIds: ['grp_financeiro'],
    createdAt: '2026-05-01T10:11:00Z',
  },
  {
    id: 'cat_politica',
    companyId: CURRENT_COMPANY_ID,
    name: 'Política Interna',
    icon: 'shield-check',
    accessGroupIds: ['grp_rh', 'grp_diretoria'],
    notifyGroupIds: ['grp_rh'],
    createdAt: '2026-05-01T10:12:00Z',
  },
  {
    id: 'cat_boleto',
    companyId: CURRENT_COMPANY_ID,
    name: 'Boleto',
    icon: 'file-invoice',
    accessGroupIds: ['grp_financeiro'],
    notifyGroupIds: ['grp_financeiro'],
    createdAt: '2026-05-01T10:13:00Z',
  },
  {
    id: 'cat_proposta',
    companyId: CURRENT_COMPANY_ID,
    name: 'Proposta Comercial',
    icon: 'file-text',
    accessGroupIds: ['grp_compras', 'grp_diretoria'],
    notifyGroupIds: ['grp_compras'],
    createdAt: '2026-05-01T10:14:00Z',
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud_1',
    companyId: CURRENT_COMPANY_ID,
    action: 'Mariana Ferreira aprovou Carlos Souza',
    actor: 'Mariana Ferreira',
    target: 'Carlos Souza',
    createdAt: '2026-02-10T10:30:00Z',
  },
  {
    id: 'aud_2',
    companyId: CURRENT_COMPANY_ID,
    action: 'Mariana Ferreira adicionou Carlos Souza ao grupo Financeiro',
    actor: 'Mariana Ferreira',
    target: 'Carlos Souza',
    createdAt: '2026-02-10T10:35:00Z',
  },
  {
    id: 'aud_3',
    companyId: CURRENT_COMPANY_ID,
    action: 'Mariana Ferreira removeu o acesso do grupo RH à categoria Política Interna',
    actor: 'Mariana Ferreira',
    target: 'Política Interna',
    createdAt: '2026-05-15T16:00:00Z',
  },
];
